name: coatt_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=9.2=0
  - cudnn=7.3.1=cuda9.2_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py36he6710b0_0
  - pillow=6.0.0=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - pycparser=2.19=py36_0
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.0=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - efficientnet-pytorch==0.6.3
    - entrypoints==0.3
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.26.0
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.5.0
    - imgaug==0.4.0
    - importlib-metadata==1.5.0
    - ipykernel==5.1.4
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.16.0
    - jinja2==2.11.1
    - joblib==0.13.2
    - jsonpatch==1.24
    - jsonpointer==2.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.1.0
    - jupyter-core==4.6.2
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.0
    - mistune==0.8.4
    - munch==2.5.0
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - networkx==2.3
    - notebook==6.0.3
    - oauthlib==3.1.0
    - opencv-python==4.1.2.30
    - overboard==0.2.0
    - pandocfilters==1.4.2
    - parso==0.6.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pretrainedmodels==0.7.4
    - progressbar==2.5
    - progressbar2==3.47.0
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.3
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.5.2
    - pyparsing==2.4.0
    - pyqt5==5.13.1
    - pyqt5-sip==12.7.0
    - pyqtgraph==0.10.0
    - pyquaternion==0.9.5
    - pyrsistent==0.15.7
    - python-utils==2.3.0
    - pywavelets==1.0.3
    - pyyaml==5.1.2
    - pyzmq==18.1.0
    - qtconsole==4.6.0
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.2
    - scipy==1.3.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - shapely==1.7.0
    - sklearn==0.0
    - tabulate==0.8.3
    - tensorboard==2.1.0
    - tensorboardx==2.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.4.0
    - torchfile==0.1.0
    - torchnet==0.0.4
    - torchvision==0.5.0
    - tornado==6.0.3
    - traitlets==4.3.3
    - urllib3==1.25.5
    - visdom==0.1.8.9
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - werkzeug==0.16.1
    - widgetsnbextension==3.5.1
    - zipp==2.2.0
